model:
  base_learning_rate: 1.0e-4
  target: sgm.models.diffusion.DiffusionEngine
  params:
    use_ema: True
    ema_decay_rate: 0.999
    denoiser_config:
      target: sgm.modules.diffusionmodules.denoiser.Denoiser
      params:
        weighting_config:
          target: sgm.modules.diffusionmodules.denoiser_weighting.EDMWeighting
          params:
            sigma_data: 1.0
        scaling_config:
          target: sgm.modules.diffusionmodules.denoiser_scaling.EDMScaling
          params:
            sigma_data: 1.0

    network_config:
      target: sgm.modules.diffusionmodules.openaimodel.UNetModel
      # reference: https://github.com/openai/guided-diffusion#classifier-guidance
      params:
        use_checkpoint: True
        in_channels: 3
        out_channels: 3
        model_channels: 256
        attention_resolutions: []
        num_res_blocks: 2
        channel_mult: [1, 2, 4, 4 ]
        num_head_channels: 64

    first_stage_config:
      target: sgm.models.autoencoder.IdentityFirstStage

    loss_fn_config:
      target: sgm.modules.diffusionmodules.loss.StandardDiffusionLoss
      params:
        sigma_sampler_config:
          target: sgm.modules.diffusionmodules.sigma_sampling.EDMSampling

    sampler_config:
      target: sgm.modules.diffusionmodules.sampling.EulerEDMSampler
      params:
        num_steps: 50

        discretization_config:
          target: sgm.modules.diffusionmodules.discretizer.EDMDiscretization

data:
  target: sgm.data.image.ImageLoader
  params:
    image_dir: "/fsx/proj-jp-stable-diffusion/data/FFHQ"
    batch_size: 8
    num_workers: 10
    transforms:
      - target: torchvision.transforms.Resize
        params:
          size: 256
          interpolation: 3
      - target: torchvision.transforms.ToTensor
    rescaled: True

lightning:
  modelcheckpoint:
    params:
      every_n_train_steps: 10000
    image_logger:
      target: main.ImageLogger
      params:
        disabled: False
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: False
        log_first_step: False
        log_images_kwargs:
          use_ema_scope: False
          N: 8
          n_rows: 2

  trainer:
    devices: 0,
    benchmark: True
    num_sanity_val_steps: 0
    accumulate_grad_batches: 4
    max_epochs: 1000
